name: Deploy to IIS

on:
  push:
    branches:
      - main  # Trigger this action when code is pushed to the main branch

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build React app
      - name: Build React app
        run: |
          npm install
          npm run build

      # Package application
      - name: Package Application
        run: |
          mkdir output
          zip -r output/ReactApp.zip ./build

      # Deploy to IIS
      - name: Deploy to IIS
        env:
          IIS_USERNAME: ${{ secrets.IIS_USERNAME }}
          IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}
          IIS_SERVER: ${{ secrets.IIS_SERVER }}
          IIS_SITE: ${{ secrets.IIS_SITE }}
        run: |
          msdeploy -verb:sync -source:package='output/ReactApp.zip' -dest:auto,computerName=$IIS_SERVER,username=$IIS_USERNAME,password=$IIS_PASSWORD,authtype=Basic -setParam:name='IIS Web Application Name',value='$IIS_SITE'
