name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Build React App
        run: |
          npm run build

      # Set up the PATH for MSDeploy
      - name: Add MSDeploy to PATH
        run: |
          echo "C:\Program Files\IIS\Microsoft Web Deploy V3" >> $GITHUB_PATH

      # Optional: Check PATH to verify if MSDeploy path is set
      - name: Check PATH
        run: |
          echo $Env:PATH

      - name: Package Application
        run: |
          mkdir output
          powershell -Command "Compress-Archive -Path ./build/* -DestinationPath ./output/ReactApp.zip"

      - name: Deploy to IIS
        env:
          IIS_USERNAME: ${{ secrets.IIS_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          IIS_SERVER: ${{ secrets.IIS_SERVER }}
          IIS_SITE: ${{ secrets.IIS_SITE }}
        run: |
          # Save the SSH key to a temporary file
          $sshKeyPath = "$env:TEMP\id_rsa"
          [System.IO.File]::WriteAllText($sshKeyPath, $env:SSH_PRIVATE_KEY)
          # Set the correct permissions for the SSH key
          icacls $sshKeyPath /inheritance:r
          icacls $sshKeyPath /grant:r "$($env:USERNAME):(R)"

          # Run the msdeploy command
          powershell -Command "& 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe' -verb:sync -source:package='output/ReactApp.zip' -dest:auto,computerName='$IIS_SERVER',username='$IIS_USERNAME',key='$sshKeyPath',authtype=ssh -setParam:name='ActionTest',value='$IIS_SITE'"
