name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the PATH for MSDeploy
      - name: Add MSDeploy to PATH
        run: |
          echo "C:\Program Files\IIS\Microsoft Web Deploy V3" # Adjust this path if your MSDeploy is installed elsewhere

      - name: Package Application
        run: |
          mkdir output
          powershell -Command "Compress-Archive -Path ./build/* -DestinationPath ./output/ReactApp.zip"

      - name: Deploy to IIS
        env:
          IIS_USERNAME: ${{ secrets.IIS_USERNAME }}
          IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}
          IIS_SERVER: ${{ secrets.IIS_SERVER }}
          IIS_SITE: ${{ secrets.IIS_SITE }}
        run: |
          msdeploy -verb:sync -source:package='output/ReactApp.zip' -dest:auto,computerName=$IIS_SERVER,username=$IIS_USERNAME,password=$IIS_PASSWORD,authtype=Basic -setParam:name='IIS Web Application Name',value='$IIS_SITE'
