name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Build React App
        run: |
          npm run build

      # Set up the PATH for MSDeploy
      - name: Add MSDeploy to PATH
        run: |
          echo "C:\Program Files\IIS\Microsoft Web Deploy V3" >> $GITHUB_PATH

      # Optional: Check PATH to verify if MSDeploy path is set
      - name: Check PATH
        run: |
          echo $Env:PATH

      - name: Package Application
        run: |
          mkdir output
          powershell -Command "Compress-Archive -Path ./build/* -DestinationPath ./output/ReactApp.zip"

      - name: Deploy to IIS
        env:
          IIS_SERVER: ${{ secrets.IIS_SERVER }}
          IIS_USER: ${{ secrets.IIS_USER }}
          IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}
          DESTINATION_PATH: ${{ secrets.DESTINATION_PATH }}
        run: |
          echo "Deploying to IIS server..."
      
          echo $securePassword
         
