name: Deploy React App to IIS

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can use 'windows-latest' if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust this to your needs

      - name: Install dependencies and build the app
        run: |
          npm install
          npm run build

      - name: Deploy to IIS
        env:
          IIS_SERVER: ${{ secrets.IIS_SERVER }}  # Set this secret in GitHub
          IIS_USER: ${{ secrets.IIS_USER }}      # Set this secret in GitHub
          IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }} # Set this secret in GitHub
          DESTINATION_PATH: ${{ secrets.DESTINATION_PATH }} # Set this secret in GitHub
        run: |
          echo "Deploying to IIS server..."
          # Use PowerShell to copy files to the IIS server
          pwsh -Command "
          $session = New-PSSession -ComputerName $env:IIS_SERVER -Credential (New-Object System.Management.Automation.PSCredential($env:IIS_USER, (ConvertTo-SecureString $env:IIS_PASSWORD -AsPlainText -Force)))
          Copy-Item -Path './build/*' -Destination $env:DESTINATION_PATH -Recurse -ToSession $session
          Remove-PSSession -Session $session
          "
